// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAE4LceV06mNhoecCOonLO_MlH3L5L1AQ',
    appId: '1:441614038266:web:9537a53a0242c5347bc543',
    messagingSenderId: '441614038266',
    projectId: 'khabar-app-b0248',
    authDomain: 'khabar-app-b0248.firebaseapp.com',
    storageBucket: 'khabar-app-b0248.firebasestorage.app',
    measurementId: 'G-FKM5VKQYWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2gUbqljceWgvHEWdYXE1_2fngBWLqEV4',
    appId: '1:441614038266:android:cc8aee92984343a27bc543',
    messagingSenderId: '441614038266',
    projectId: 'khabar-app-b0248',
    storageBucket: 'khabar-app-b0248.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAp8aGcSTO4lW8HtomLbss_3xjFBynroI',
    appId: '1:441614038266:ios:41a57fe5e61005897bc543',
    messagingSenderId: '441614038266',
    projectId: 'khabar-app-b0248',
    storageBucket: 'khabar-app-b0248.firebasestorage.app',
    iosBundleId: 'com.example.apiTesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAp8aGcSTO4lW8HtomLbss_3xjFBynroI',
    appId: '1:441614038266:ios:41a57fe5e61005897bc543',
    messagingSenderId: '441614038266',
    projectId: 'khabar-app-b0248',
    storageBucket: 'khabar-app-b0248.firebasestorage.app',
    iosBundleId: 'com.example.apiTesting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAE4LceV06mNhoecCOonLO_MlH3L5L1AQ',
    appId: '1:441614038266:web:56eabd069d0e4e157bc543',
    messagingSenderId: '441614038266',
    projectId: 'khabar-app-b0248',
    authDomain: 'khabar-app-b0248.firebaseapp.com',
    storageBucket: 'khabar-app-b0248.firebasestorage.app',
    measurementId: 'G-EK13918TYS',
  );
}
